#  This file defines the service on Render

services:
  - type: web
    name: student-portal-angular
    runtime: docker
    # Render will use the Dockerfile
    dockerfilePath: ./Dockerfile
    # Branch monitored for auto-deploy
    branch: main
    # Free plan
    plan: free
    # Health check endpoint
    healthCheckPath: /
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
